## M1 T02: Exploración y estructura de los datos - Dataframes con Pandas

Cargamos el archivo CSV.

In [78]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#cargamos el data set a un dataframe de pandas
df=pd.read_csv(r'C:\Users\wcc30\Desktop\DelayedFlights.csv')

#info
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1936758 entries, 0 to 1936757
Data columns (total 30 columns):
 #   Column             Dtype
---  ------             -----
 0   Unnamed: 0         int64
 1   Year               int64
 2   Month              int64
 3   DayofMonth         int64
 4   DayOfWeek          int64
 5   DepTime            float64
 6   CRSDepTime         int64
 7   ArrTime            float64
 8   CRSArrTime         int64
 9   UniqueCarrier      object
 10  FlightNum          int64
 11  TailNum            object
 12  ActualElapsedTime  float64
 13  CRSElapsedTime     float64
 14  AirTime            float64
 15  ArrDelay           float64
 16  DepDelay           float64
 17  Origin             object
 18  Dest               object
 19  Distance           int64
 20  TaxiIn             float64
 21  TaxiOut            float64
 22  Cancelled          int64
 23  CancellationCode   object
 24  Diverted           int64
 25  CarrierDelay       float64
 26  WeatherDelay       float64
 27  NASDelay           float64
 28  SecurityDelay      float64
 29  LateAircraftDelay  float64
dtypes: float64(14), int64(11), object(5)
memory usage: 443.3+ MB

Hemos decidido primero comenzar con el calculo de datos missing para tener mayor criterio y una causalidad para eliminar variables innecesarias que podrían afectar por su gran cantidad de datos missing.

In [79]:
#Calculamos la suma de los datos faltantes de los datos missing de cada variable:
print("Suma de datos missing:\n", df.isnull().sum())

#Prefiero mejor visualizar los datos missings en %, ya que nos permite tener un mejor análisis de ellos
print("\nPorcentaje de datos missing % :\n", round((df.isnull().sum()*100/df.shape[0]),2))

Suma de datos missing:
 Unnamed: 0                0
Year                      0
Month                     0
DayofMonth                0
DayOfWeek                 0
DepTime                   0
CRSDepTime                0
ArrTime                7110
CRSArrTime                0
UniqueCarrier             0
FlightNum                 0
TailNum                   5
ActualElapsedTime      8387
CRSElapsedTime          198
AirTime                8387
ArrDelay               8387
DepDelay                  0
Origin                    0
Dest                      0
Distance                  0
TaxiIn                 7110
TaxiOut                 455
Cancelled                 0
CancellationCode          0
Diverted                  0
CarrierDelay         689270
WeatherDelay         689270
NASDelay             689270
SecurityDelay        689270
LateAircraftDelay    689270
dtype: int64

Porcentaje de datos missing % :
 Unnamed: 0            0.00
Year                  0.00
Month                 0.00
DayofMonth            0.00
DayOfWeek             0.00
DepTime               0.00
CRSDepTime            0.00
ArrTime               0.37
CRSArrTime            0.00
UniqueCarrier         0.00
FlightNum             0.00
TailNum               0.00
ActualElapsedTime     0.43
CRSElapsedTime        0.01
AirTime               0.43
ArrDelay              0.43
DepDelay              0.00
Origin                0.00
Dest                  0.00
Distance              0.00
TaxiIn                0.37
TaxiOut               0.02
Cancelled             0.00
CancellationCode      0.00
Diverted              0.00
CarrierDelay         35.59
WeatherDelay         35.59
NASDelay             35.59
SecurityDelay        35.59
LateAircraftDelay    35.59
dtype: float64

Podemos observar que "CarrierDelay", "WeatherDealy", "NASDelay", "SecurityDelay", "LateAircraftDelay" son las variables que tienen un porcentaje altos de datos missing, por lo cual seran las primeros que eliminaremos. 

Otras variables que decidimos eliminar son: 

-"Cancelled", debido a que hay otra variable similar codificada "CancellationCode".

-"DayOfWeek", dias de la semana son datos irrelevantes.

-"Unnamed: 0"

-"TaxiIn", datos irrelevantes para posterior análisis.

-"TaxiOut", datos irrelevantes para posterior análisis.

Las demás variables que tienen NAs, debido a que es minimo el porcentaje de datos faltantes que tienen, realizaremos la eliminacion de estos datos.

In [80]:
#Eliminamos los NAs restantes
df= df.dropna()

#Eliminamos los registros duplicados
df = df.drop_duplicates()

Agruparemos 3 variables: "Year" , "Month" y "DayofMonth" en una sola variable "Data", para posteiormente eliminar las 3 primeras mencionadas

In [81]:
df['Data'] = df['DayofMonth'].map(str) + '-' + df['Month'].map(str) + '-' + df['Year'].map(str)
df.sort_values(['Data'])

,Unnamed: 0,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,...,TaxiOut,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,Data
110966,354266,2008,1,1,2,1058.0,1050,1345.0,1312,FL,...,10.0,0,N,0,8.0,0.0,25.0,0.0,0.0,1-1-2008
127482,413189,2008,1,1,2,836.0,815,1020.0,920,MQ,...,7.0,0,N,0,0.0,0.0,39.0,0.0,21.0,1-1-2008
127481,413188,2008,1,1,2,656.0,625,849.0,740,MQ,...,59.0,0,N,0,0.0,31.0,38.0,0.0,0.0,1-1-2008
127455,413134,2008,1,1,2,1202.0,1050,1154.0,1045,MQ,...,8.0,0,N,0,0.0,0.0,0.0,0.0,69.0,1-1-2008
127424,413073,2008,1,1,2,703.0,635,654.0,620,MQ,...,14.0,0,N,0,28.0,0.0,6.0,0.0,0.0,1-1-2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1469264,5060677,2008,9,9,2,1744.0,1414,149.0,2238,UA,...,12.0,0,N,0,141.0,0.0,0.0,0.0,50.0,9-9-2008
1509108,5305041,2008,9,9,2,1423.0,1240,1708.0,1450,AA,...,18.0,0,N,0,0.0,0.0,37.0,0.0,101.0,9-9-2008
1519244,5357679,2008,9,9,2,1914.0,1700,2122.0,1900,CO,...,27.0,0,N,0,0.0,0.0,38.0,0.0,104.0,9-9-2008
1519395,5358476,2008,9,9,2,1508.0,1241,1811.0,1515,CO,...,34.0,0,N,0,0.0,0.0,176.0,0.0,0.0,9-9-2008
1449037,4955647,2008,9,9,2,2129.0,1930,2250.0,2118,XE,...,22.0,0,N,0,92.0,0.0,0.0,0.0,0.0,9-9-2008

Eliminamos las variables

In [82]:
df = df.drop(['CarrierDelay', 'WeatherDelay', 'NASDelay', 'SecurityDelay',
         'LateAircraftDelay', 'Unnamed: 0', 'DayOfWeek', 'Cancelled'
        , 'TaxiIn', 'TaxiOut','Year', 'Month', 'DayofMonth'], axis=1)

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1247486 entries, 3 to 1936755
Data columns (total 18 columns):
 #   Column             Non-Null Count    Dtype
---  ------             --------------    -----
 0   DepTime            1247486 non-null  float64
 1   CRSDepTime         1247486 non-null  int64
 2   ArrTime            1247486 non-null  float64
 3   CRSArrTime         1247486 non-null  int64
 4   UniqueCarrier      1247486 non-null  object
 5   FlightNum          1247486 non-null  int64
 6   TailNum            1247486 non-null  object
 7   ActualElapsedTime  1247486 non-null  float64
 8   CRSElapsedTime     1247486 non-null  float64
 9   AirTime            1247486 non-null  float64
 10  ArrDelay           1247486 non-null  float64
 11  DepDelay           1247486 non-null  float64
 12  Origin             1247486 non-null  object
 13  Dest               1247486 non-null  object
 14  Distance           1247486 non-null  int64
 15  CancellationCode   1247486 non-null  object
 16  Diverted           1247486 non-null  int64
 17  Data               1247486 non-null  object
dtypes: float64(7), int64(5), object(6)
memory usage: 180.8+ MB

Como pudimos ver inicialmente en la info del dataframe,las variables "Diverted" y "FlightNum" estan reconocidas como variables numéricas por lo cual las definimos como categóricas para no tener valores erróneos al realizar el resúmen estadístico de las variables númericas.

In [83]:
df['Diverted'] = df['Diverted'].astype('category')
df['FlightNum'] = df['FlightNum'].astype('category')

In [84]:
df.describe().applymap("{0:.2f}".format)

,DepTime,CRSDepTime,ArrTime,CRSArrTime,ActualElapsedTime,CRSElapsedTime,AirTime,ArrDelay,DepDelay,Distance
count,1247486.00,1247486.00,1247486.00,1247486.00,1247486.00,1247486.00,1247486.00,1247486.00,1247486.00,1247486.00
mean,1558.83,1487.95,1616.75,1652.46,135.38,131.76,107.42,63.29,59.68,741.59
std,454.33,421.18,583.94,461.74,72.30,69.53,68.17,60.75,59.87,559.36
min,1.00,0.00,1.00,0.00,14.00,-21.00,0.00,15.00,6.00,11.00
25%,1232.00,1150.00,1326.00,1340.00,83.00,80.00,58.00,26.00,24.00,334.00
50%,1618.00,1529.00,1737.00,1722.00,118.00,115.00,90.00,43.00,41.00,595.00
75%,1924.00,1830.00,2048.00,2022.00,167.00,161.00,136.00,79.00,75.00,972.00
max,2400.00,2359.00,2400.00,2359.00,1114.00,660.00,1091.00,2461.00,2467.00,4962.00

Creamos la nueva variable "Delayed" (Retraso)

In [85]:
#Añadimos la columna Delayed,si ha llegado tarde (True) y sino (False)
df['Delayed']=df.ActualElapsedTime>df.CRSElapsedTime

df[['ActualElapsedTime','CRSElapsedTime','Delayed']].head(10)

    ActualElapsedTime  CRSElapsedTime  Delayed
3                90.0            90.0    False
5               240.0           250.0    False
7               121.0           135.0    False
9               228.0           240.0    False
11              123.0           135.0    False
12               56.0            70.0    False
13               57.0            70.0    False
17              155.0           195.0    False
19              147.0           165.0    False
23              135.0           145.0    False

Creamos la variable "veloc_mean" (Velocidad Media)

In [86]:
df['veloc_mean']=round(df['Distance']*60/df['AirTime'],2)

df.groupby('UniqueCarrier')[['UniqueCarrier','veloc_mean']].head()

       UniqueCarrier  veloc_mean
3                 WN      401.30
5                 WN      415.04
7                 WN      464.30
9                 WN      419.44
11                WN      457.09
...              ...         ...
172623            CO      437.01
172624            CO      390.97
172628            CO      479.44
172629            CO      356.39
172631            CO      501.45

[100 rows x 2 columns]

¿Cuáles son los vuelos más largos?

In [87]:
vuelos_largos = df[['FlightNum','Origin','Dest','Distance']].groupby(['Distance']).first().reset_index()
vuelos_largos.sort_values(by=['Distance'],ascending=False)[:10]

      Distance FlightNum Origin Dest
1403      4962        15    EWR  HNL
1402      4502       850    HNL  ATL
1401      4243         1    ORD  HNL
1400      4213         3    KOA  ORD
1399      4184         3    ORD  OGG
1398      3972       808    HNL  MSP
1397      3904        73    IAH  HNL
1396      3784         5    DFW  HNL
1395      3711         6    OGG  DFW
1394      3417      1039    ATL  ANC

¿Y los más atrasados?

In [88]:
#Atraso en la llegada:
df[['FlightNum','UniqueCarrier','Origin','Dest','ArrDelay']].sort_values(by='ArrDelay',ascending=False)[:10]

        FlightNum UniqueCarrier Origin Dest  ArrDelay
322516        808            NW    HNL  MSP    2461.0
686014       1699            NW    CLT  MSP    2453.0
839306       1107            NW    RSW  DTW    1951.0
1009553      3538            MQ    LIT  DFW    1707.0
1881639       357            NW    BOS  MSP    1655.0
1497823       512            NW    OMA  MSP    1583.0
685437       1472            NW    MOT  MSP    1542.0
163379       2398            AA    EGE  MIA    1525.0
1214839       804            NW    SEA  MSP    1510.0
521096       1743            NW    BNA  MEM    1490.0

In [89]:
#Atraso en la salida:
df[['FlightNum','UniqueCarrier','Origin','Dest','DepDelay']].sort_values(by='DepDelay',ascending=False)[:10]

        FlightNum UniqueCarrier Origin Dest  DepDelay
686014       1699            NW    CLT  MSP    2467.0
322516        808            NW    HNL  MSP    2457.0
839306       1107            NW    RSW  DTW    1952.0
1009553      3538            MQ    LIT  DFW    1710.0
1881639       357            NW    BOS  MSP    1597.0
1497823       512            NW    OMA  MSP    1552.0
685437       1472            NW    MOT  MSP    1545.0
545038       2093            AA    LGA  MIA    1521.0
1214839       804            NW    SEA  MSP    1518.0
521096       1743            NW    BNA  MEM    1490.0

Tabla de los aeropuertos con mas retrasos acumulados

In [90]:
df.groupby('UniqueCarrier').sum()['Delayed'].sort_values(ascending=False).head(10)

UniqueCarrier
WN    72882
AA    69036
MQ    51490
OO    46991
UA    43553
DL    43220
XE    36454
NW    33800
CO    30203
US    29704
Name: Delayed, dtype: int64

In [ ]:
df.head(1048576).to_excel('TascaPython.xlsx')
df.to_csv('TascaPython.xlsx')